### PR TITLE
Created the bot :]

### PR DESCRIPTION
**Pull request by Itz-Hyperz**
You're welcome

### CODE REVIEW

**Comment by Bandit-code** [comment]
Your not funny hyperz but I was gonna use a multi ban system just been very busy

**Comment by Itz-Hyperz** [comment]
should be good now :]

**Comment by Itz-Hyperz** [comment]
feel free to merge @Bandit-code 

- [X] ~~**Add Linux Compatibility**~~ [03-22-2021]
- [X] ~~**Add Anus to List**~~ [03-22-2021]
- [X] ~~**Code Actual Bot**~~ [03-20-2021]

**Comment by Bandit-code** [comment]
This is petty funny not gonna lie I am gonna look over it and edit;/add what ever latter but this is funny hyperz one thing I like about you!

**Pull request merged**
